[target.wasm32-unknown-unknown]
runner = 'wasm-bindgen-test-runner'

[alias]
wasm = "build -p rings-core --target=wasm32-unknown-unknown --features wasm --no-default-features"
test-wasm = "test -p rings-core --target=wasm32-unknown-unknown --features wasm --no-default-features"
