[package]
name = "rings-node"
version = "0.2.1"
edition = "2021"
default-run = "rings"
authors = ["RND <dev@ringsnetwork.io>"]
description = "Chord DHT implementation with ICE"
repository = "https://github.com/RingsNetwork/rings-node"
license = "GPL-3.0"
readme = "README.md"
keywords = ["Chord", "DHT", "Web3", "P2P", "WASM"]
categories = ["network-programming", "cryptography", "wasm"]

[workspace]
members = ["rings-core"]

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["node"]
node = [
    "tokio",
    "hyper",
    "axum",
    "tower-http",
    "clap",
    "reqwest",
    "form_urlencoded",
    "pin-project",
    "rings-core",
]
browser = [
    "console_error_panic_hook",
    "reqwest-wasm",
    "rings-core-wasm",
    "console_log",
]
browser_chrome_test = ["browser"]

[dependencies]
anyhow = "1.0.45"
arrayref = "0.3.6"
async-trait = "0.1.52"
base64 = { version = "0.13.0" }
chrono = "0.4.19"
dotenv = "0.15.0"
futures = "0.3.21"
http = { version = "0.2.6" }
jsonrpc-core = { version = "18.0.0" }
jsonrpc-pubsub = { version = "18.0.0" }
log = { version = "0.4", features = ["std"] }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.70"
thiserror = "1"

# client
axum = { version = "0.5.16", optional = true }
clap = { version = "3.1.6", features = ["derive", "env"], optional = true }
form_urlencoded = { version = "1.0.1", optional = true }
hyper = { version = "0.14.14", features = ["full"], optional = true }
pin-project = { version = "1", optional = true }
reqwest = { version = "0.11", features = ["json"], optional = true }
rings-core = { package = "rings-core", path = "./rings-core", optional = true, version = "0.2.1" }
tokio = { version = "1.13.0", features = ["full"], optional = true }
tower-http = { version = "0.3.4", features = ["cors"], optional = true }

# browser
console_error_panic_hook = { version = "0.1.1", optional = true }
console_log = { version = "0.2", optional = true }
reqwest-wasm = { version = "0.11", features = ["json"], optional = true }
rings-core-wasm = { package = "rings-core", path = "./rings-core", features = ["wasm"], default-features = false, optional = true, version = "0.2.1" }

[dev-dependencies]
console_log = { version = "0.2" }
fluvio-wasm-timer = "0.2.5"
wasm-bindgen-test = { version = "0.3.0" }

[[bin]]
name = "rings"
path = "bin/rings.rs"
required-features = ["node"]
