[package]
name = "bns-node"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "bns-core",
]

[dependencies]
anyhow = "1.0.45"
clap = { version="3", features = ["derive"]}
env_logger = { version = "0.9.0"}
hyper = { version = "0.14.14", features = ["full"]}
toml = "0.5.8"
log = "0.4"

tokio = { version = "1.13.0", features = ["full"]}
tokio-util = { version = "0.6.9"}

bns-core = {path="./bns-core"}
