[package]
name = "rings-node"
version = "0.2.3"
edition = "2021"
default-run = "rings"
authors = ["RND <dev@ringsnetwork.io>"]
description = "Chord DHT implementation with ICE"
repository = "https://github.com/RingsNetwork/rings-node"
license = "GPL-3.0"
readme = "README.md"
keywords = ["Chord", "DHT", "Web3", "P2P", "WASM"]
categories = ["network-programming", "cryptography", "wasm"]

[workspace]
members = ["rings-core"]

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["node"]
node = [
    "tokio",
    "hyper",
    "axum",
    "tower-http",
    "clap",
    "reqwest",
    "form_urlencoded",
    "pin-project",
    "rings-core",
    "async-stream",
    "opentelemetry",
    "opentelemetry-jaeger",
    "backtrace",
    "serde_yaml",
    "lazy_static",
]
browser = [
    "console_error_panic_hook",
    "tracing-wasm",
    "reqwest-wasm",
    "rings-core-wasm",
]
browser_chrome_test = ["browser"]

[dependencies]
anyhow = "1.0.45"
arrayref = "0.3.6"
async-trait = "0.1.52"
base64 = { version = "0.13.0" }
bincode = "1.3.3"
bytes = { version = "1.2.1", features = ["serde"] }
chrono = "0.4.23"
dotenv = "0.15.0"
futures = "0.3.21"
futures-timer = "3.0.2"
http = { version = "0.2.6" }
jsonrpc-core = { version = "18.0.0" }
jsonrpc-pubsub = { version = "18.0.0" }
log = { version = "0.4", features = ["std"] }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.70"
thiserror = "1"
tracing = "0.1.37"
tracing-log = "0.1.3"
tracing-opentelemetry = "0.18.0"
tracing-subscriber = { version = "0.3.15", features = ["ansi"] }

# node
async-stream = { version = "0.3.2", optional = true }
axum = { version = "0.6.6", optional = true }
backtrace = { version = "0.3.6", optional = true }
clap = { version = "4.0.14", features = ["derive", "env"], optional = true }
form_urlencoded = { version = "1.0.1", optional = true }
hyper = { version = "0.14.14", features = ["full"], optional = true }
lazy_static = { version = "1.4.0", optional = true }
opentelemetry = { version = "0.18.0", default-features = false, features = ["trace", "rt-tokio"], optional = true }
opentelemetry-jaeger = { version = "0.17.0", features = ["rt-tokio"], optional = true }
pin-project = { version = "1", optional = true }
reqwest = { version = "0.11", features = ["json", "rustls-tls"], optional = true, default-features = false }
rings-core = { package = "rings-core", path = "./rings-core", optional = true, version = "0.2.3" }
serde_yaml = { version = "0.9.17", optional = true }
tokio = { version = "1.13.0", features = ["full"], optional = true }
tower-http = { version = "0.3.4", features = ["cors"], optional = true }

# browser
console_error_panic_hook = { version = "0.1.1", optional = true }
reqwest-wasm = { version = "0.11", features = ["json", "rustls-tls"], optional = true, default-features = false }
rings-core-wasm = { package = "rings-core", path = "./rings-core", features = ["wasm"], default-features = false, optional = true, version = "0.2.3" }
tracing-wasm = { version = "0.2.1", optional = true }

[dev-dependencies]
fluvio-wasm-timer = "0.2.5"
wasm-bindgen-test = { version = "0.3.0" }

[[bin]]
name = "rings"
path = "bin/rings.rs"
required-features = ["node"]
