[package]
name = "rings"
version = "0.2.4"
edition = "2021"
authors = ["RND <dev@ringsnetwork.io>"]
description = """
Rings is a structured peer-to-peer network implementation using WebRTC, Chord algorithm, and full WebAssembly (WASM) support.
"""
repository = "https://github.com/RingsNetwork/rings-node"
license = "GPL-3.0"
readme = "README.md"
keywords = ["Chord", "DHT", "Web3", "P2P", "WASM"]
categories = ["network-programming", "cryptography", "wasm"]

[workspace]
members = ["core", "node"]
default-members = ["node"]