[workspace]
members = ["core", "transport", "node", "rpc", "derive"]

resolver = "2"

[workspace.dependencies]
rings-core = { version = "0.3.0", path = "core", default-features = false }
rings-derive = { version = "0.3.0", path = "derive", default-features = false }
rings-rpc = { version = "0.3.0", path = "rpc", default-features = false }
rings-transport = { version = "0.3.0", path = "transport" }
wasm-bindgen = { version = "0.2.87" }
wasm-bindgen-macro-support = { version = "0.2.84" }
