[workspace]
members = ["core", "node", "rpc", "derive", "extension"]

resolver = "2"

[workspace.dependencies]
wasm-bindgen = { version = "=0.2.84" }
wasm-bindgen-macro-support = { version = "=0.2.84" }
