[package]
name = "bns-node"
version = "0.1.0"
edition = "2021"
default-run = "bns-node"

[workspace]
members = ["bns-core"]

[dependencies]
lazy_static = "1.4.0"
webrtc = { version = "0.3.3" }
tokio = { version = "1.13.0", features = ["full"] }
hyper = { version = "0.14.14", features = ["full"] }
tonic = { version = "0.6.2", features = ["tls", "tls-roots", "prost", "compression"] }
env_logger = { version = "0.9.0" }
tokio-util = { version = "0.6.9" }
tower = { version = "0.4.12", features = ["full"] }
tower-http = { version="0.2.4", features = ["set-header"]}
prost = "0.9.0"
http = "0.2.6"
clap = { version = "3", features = ["derive", "env"] }
anyhow = "1.0.45"
bns-core = { path = "./bns-core" }
reqwest = { version = "0.11", features = ["json"] }
form_urlencoded = "1.0.1"
toml = "0.5.8"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.70"
log = "0.4"
futures = "0.3.21"
web3 = { version = "0.18.0" }
secp256k1 = "0.21"
axum = "0.4.7"
dotenv = "0.15.0"
pin-project = "1"
base64 = "0.13.0"
arrayref = "0.3.6"
uuid = { version = "0.8.2", features = ["v4"]}
daemonize = "0.4.1"
libc = "0.2.121"

[[bin]]
name = "bns-node"
path = "bin/main.rs"

[[bin]]
name = "bns-node-daemon"
path = "bin/daemon.rs"

[build-dependencies]
tonic-build = { version = "0.6.2", features = ["prost", "compression"] }
