session_sk: MbZTWnsWh4SKRSDzTDJ1VtLJe6Yc4zH8MAiyAHLsKeax9jHvHR7dkXDAbrNicfo7vg9jXX5fR7sTSJ8DH7pfDGXrARxJPHbLcdvHdC9TGHAHS9MbZBaYuJ51WA6vvdp35yzFHRn2KggKFf5Hxax5FxFezt9bcAj9xnzfSHvqqsnb4vCyHvqqtTr181d6mazWwvAm9gKJoNpe9fnzd94VCjK11DPwLUicPtsDCbJA5349CRExen9ZnDgR6osctJFXWqCTj88B9Q1BBckXRA7AZeUSt3tnEw8Pkw8vH7oyu9EE8CqDdhJK9EE5iRKnbEB9ER2e39E1fEA4xbBqMMiVv9ENqA4FGCKzAEd4jSpjS7v8PkycRx9tGj9PtZFMfSbcu9u4vn85SwBF9tqnsdYnET38PsX4kUbHV19ZSWMCtmfsP9Q17D819Lkh9ZpNgDdCxSL94LRK3xoA7qAPwrugYwEEt8Pij9iT65aT9ZnBBfqG6Nc9Q3JgzZSECQA4hCpjwbeu79tzXpVfKvwMAZeWw4eu2tj9ELk969tH959u9KjR1uiX29Zra9rs5HmR8Pj6iLnGBnA6j3ePB4aUX6AQ71jztHTfcAa2t93WL7959QAP2wHAahQ9G6CAz3WtqcAQMzCxtXjP3A533eCaFNbnHRYtX5bUnmMHFzyJZkyxHX3B
bind: 127.0.0.1:50001
endpoint_url: http://127.0.0.1:50001
ice_servers: stun://stun.l.google.com:19302
stabilize_timeout: 3
external_ip: null
backend: []
data_storage:
  path: /Users/ryan/.rings/data2
  capacity: 200000000
measure_storage:
  path: /Users/ryan/.rings/measure2
  capacity: 200000000
extension:
  paths: []
